import architecture from "../Images/profesionales/arquitectura.jpg";
import installation from "../Images/profesionales/instalacion.jpg";
import training from "../Images/profesionales/asesoramiento-en-obra.jpg";
import systems from "../Images/profesionales/revision-sistemas.jpg";

export const serviceAssets = {
  suministro: { image: architecture, query: "suministro" },
  "apoyo-tecnico": { image: systems, query: "apoyo-tecnico" },
  instalacion: { image: installation, query: "instalacion" },
  "asesoramiento-tecnico": { image: training, secondaryImage: systems, query: "asistencia-en-obra" },
};
export const serviceCopy = {
  es: {
    suministro: {
      label: "Solo suministro", title: "Suministro de ventanas para profesionales.",
      description: "Ventanas de PVC y aluminio configuradas para empresas de reforma y construcción en Cataluña. Condiciones profesionales y entrega en obra.",
      intro: "Tú te encargas de instalar. Nosotros te suministramos la carpintería que necesita tu proyecto, configurada según las características de la obra.",
      fit: "Para empresas que ya cuentan con instaladores y quieren un colaborador para resolver el suministro de ventanas.",
      includes: [["Carpinterías a medida", "Configuración de ventanas de PVC y aluminio según medidas, aperturas y acabados del proyecto."], ["Sistemas según la obra", "Trabajamos con REHAU en PVC e INDALSU y STRUGAL en aluminio. La elección depende de las prestaciones y del presupuesto."], ["Entrega en obra", "Coordinamos contigo las necesidades de suministro y la entrega. Los plazos se concretan en cada propuesta."]],
      steps: [["Comparte tu proyecto", "Envíanos medidas, unidades, ubicación y las características que ya tengas definidas."], ["Revisamos la configuración", "Concretamos contigo sistemas, acabados y condiciones antes de confirmar el suministro."], ["Coordinamos la entrega", "Acordamos la entrega para que tu equipo pueda organizar la instalación."]],
      faq: [["¿Incluye la instalación?", "Esta modalidad está pensada para que instale tu equipo. Si quieres delegar medición e instalación, consulta la solución completa."], ["¿Puedo pedir apoyo técnico?", "Sí. Podemos ampliar la colaboración con revisión técnica y asistencia según las necesidades de la obra."], ["¿Cómo se calcula el precio?", "Preparamos una propuesta profesional según sistemas, medidas, unidades y acabados. Necesitamos los datos del proyecto para concretarla."]],
      cta: "Consultar suministro", alt: "Visualización de ventanas de aluminio en un proyecto residencial mediterráneo",
    },
    "apoyo-tecnico": {
      label: "Suministro + apoyo técnico", title: "Suministro de ventanas con apoyo técnico.",
      description: "Apoyo técnico para carpintería exterior en Cataluña: revisión de medidas, configuración y soluciones constructivas junto al suministro de PVC y aluminio.",
      intro: "Tu equipo mantiene el control de la instalación. Te acompañamos en las decisiones técnicas para que las ventanas encajen en el proyecto.",
      fit: "Para profesionales que instalan con su propio equipo y necesitan resolver medidas, encuentros o dudas de configuración.",
      includes: [["Revisión de medidas", "Revisamos contigo la información del proyecto y las dudas de medición antes de definir la carpintería."], ["Configuración y sistemas", "Te ayudamos a valorar aperturas, perfiles y prestaciones según la obra y su presupuesto."], ["Asistencia técnica", "Estudiamos las soluciones constructivas y las cuestiones que surjan. Acordamos la asistencia que necesita cada proyecto."]],
      steps: [["Identificamos la duda", "Comparte planos, fotografías, medidas y la decisión técnica que necesitas resolver."], ["Definimos la solución", "Revisamos los condicionantes contigo y concretamos la configuración de las carpinterías."], ["Acompañamos el proyecto", "Coordinamos suministro y apoyo técnico con el alcance acordado para la obra."]],
      faq: [["¿Mi equipo sigue instalando?", "Sí. En esta modalidad, tu equipo realiza la instalación y cuenta con nuestro apoyo técnico acordado."], ["¿Podéis asistir directamente en obra?", "Podemos valorar asistencia en obra según el proyecto. Si tu equipo está empezando, consulta también la primera instalación asistida."], ["¿Qué documentación conviene enviar?", "Los planos disponibles, fotografías de los huecos, medidas orientativas y las necesidades de apertura, aislamiento o acabado."]],
      cta: "Consultar apoyo técnico", alt: "Visualización de una revisión técnica de perfiles de PVC y aluminio",
    },
    instalacion: {
      label: "Suministro + instalación", title: "Instalación de ventanas para tus obras.",
      description: "Medición, suministro e instalación de carpintería exterior para empresas de reforma y construcción en Cataluña. Un único responsable para la partida.",
      intro: "Delega la partida de carpintería exterior. Nos encargamos de medir, suministrar e instalar, coordinándonos con la planificación de tu obra.",
      fit: "Para constructoras, empresas de reforma e interioristas que prefieren contar con un único responsable de la carpintería exterior.",
      includes: [["Medición y definición", "Revisamos los huecos y las necesidades del proyecto para definir la carpintería antes del suministro."], ["Suministro coordinado", "Seleccionamos y suministramos las ventanas de PVC o aluminio según la solución acordada."], ["Instalación y acabados", "Nos encargamos del montaje y los acabados de la partida, coordinando la intervención con el resto de la obra."]],
      steps: [["Conocemos la obra", "Cuéntanos la ubicación, el número de unidades y el estado del proyecto."], ["Acordamos el alcance", "Concretamos mediciones, sistema, acabados, condiciones y coordinación de la instalación."], ["Resolvemos la partida", "Organizamos suministro e instalación y revisamos el funcionamiento de la carpintería."]],
      faq: [["¿Incluye la medición?", "Sí. Esta modalidad reúne medición, suministro e instalación de la carpintería acordada."], ["¿Trabajáis con mi equipo de reforma?", "Sí. Nos coordinamos con los responsables de la obra para organizar la intervención y los encuentros con otros trabajos."], ["¿Podéis renovar carpinterías existentes?", "Sí. Estudiamos las sustituciones según el estado de los huecos y las necesidades de la reforma. El alcance se concreta en la propuesta."]],
      cta: "Consultar instalación completa", alt: "Visualización de una comprobación de nivel en la instalación de una ventana",
    },
    "asesoramiento-tecnico": {
      label: "Asesoramiento técnico en obra", title: "Asesoramiento técnico para instalar en tu obra.",
      description: "Asesoramiento técnico y acompañamiento en las primeras instalaciones de ventanas de PVC y aluminio para equipos de reforma y construcción en Cataluña.",
      intro: "Si tu empresa quiere incorporar la instalación de ventanas, acompañamos a tu equipo en sus primeros trabajos con asistencia técnica directamente en obra.",
      fit: "Para empresas que quieren desarrollar la capacidad de instalar carpintería de PVC o aluminio dentro de su propio equipo.",
      includes: [["Preparación de la instalación", "Revisamos con vuestro equipo el sistema y las cuestiones técnicas que conviene resolver antes del montaje."], ["Acompañamiento práctico", "Os ayudamos durante la primera instalación, resolviendo las dudas que surjan en el trabajo real."], ["Autonomía progresiva", "El objetivo es que vuestro equipo entienda el proceso y gane autonomía con apoyo adaptado a su experiencia."]],
      steps: [["Cuéntanos vuestro punto de partida", "Necesitamos conocer la experiencia del equipo, el sistema y las características de la primera obra."], ["Planificamos la asistencia", "Acordamos alcance, desplazamiento y acompañamiento según las unidades y necesidades del proyecto."], ["Resolvemos las dudas en obra", "Acompañamos el trabajo y resolvemos las cuestiones técnicas junto a vuestro equipo."]],
      faq: [["¿En qué consiste el asesoramiento?", "Revisamos con vuestro equipo las cuestiones técnicas de la instalación y acompañamos el trabajo en obra según el alcance acordado."], ["¿Hay un precio fijo?", "La propuesta se adapta al proyecto, desplazamiento, número de unidades y necesidades del equipo. Consúltanos para concretarla."], ["¿También suministráis las ventanas?", "Sí. Podemos combinar el suministro de carpinterías con el acompañamiento en las primeras instalaciones."]],
      cta: "Consultar asesoramiento técnico", alt: "Visualización de un técnico acompañando a otro profesional en la instalación de una ventana",
      secondaryTitle: "Entender el sistema también forma parte del trabajo.", secondaryText: "Revisar perfiles, juntas y encuentros ayuda a plantear las preguntas adecuadas antes de instalar. Adaptamos el apoyo a los sistemas y a la experiencia de tu equipo.",
    },
  },
  ca: {
    suministro: {
      label: "Només subministrament", title: "Subministrament de finestres per a professionals.",
      description: "Finestres de PVC i alumini per a empreses de reforma i construcció a Catalunya. Condicions professionals i lliurament a l’obra.",
      intro: "Tu t’encarregues d’instal·lar. Nosaltres et subministrem la fusteria que necessita el teu projecte, configurada segons les característiques de l’obra.",
      fit: "Per a empreses que ja tenen instal·ladors i volen un col·laborador per resoldre el subministrament de finestres.",
      includes: [["Fusteria a mida", "Configuració de finestres de PVC i alumini segons mides, obertures i acabats del projecte."], ["Sistemes segons l’obra", "Treballem amb REHAU en PVC i INDALSU i STRUGAL en alumini, segons les prestacions i el pressupost."], ["Lliurament a l’obra", "Coordinem les necessitats de subministrament i el lliurament. Els terminis es concreten en cada proposta."]],
      steps: [["Comparteix el projecte", "Envia’ns mides, unitats, ubicació i les característiques que ja tinguis definides."], ["Revisem la configuració", "Concretem sistemes, acabats i condicions abans de confirmar el subministrament."], ["Coordinem el lliurament", "Acordem el lliurament perquè el teu equip pugui organitzar la instal·lació."]],
      faq: [["Inclou la instal·lació?", "Aquesta modalitat està pensada perquè instal·li el teu equip. Per delegar mesurament i instal·lació, consulta la solució completa."], ["Puc demanar suport tècnic?", "Sí. Podem ampliar la col·laboració amb revisió tècnica i assistència segons les necessitats de l’obra."], ["Com es calcula el preu?", "Preparem una proposta professional segons sistemes, mides, unitats i acabats del projecte."]],
      cta: "Consultar subministrament", alt: "Visualització de finestres d’alumini en un projecte residencial mediterrani",
    },
    "apoyo-tecnico": {
      label: "Subministrament + suport tècnic", title: "Subministrament de finestres amb suport tècnic.",
      description: "Suport tècnic per a fusteria exterior a Catalunya: revisió de mides, configuració i solucions constructives amb subministrament de PVC i alumini.",
      intro: "El teu equip manté el control de la instal·lació. T’acompanyem en les decisions tècniques perquè les finestres encaixin en el projecte.",
      fit: "Per a professionals que instal·len amb el seu equip i necessiten resoldre mides, trobades o dubtes de configuració.",
      includes: [["Revisió de mides", "Revisem la informació del projecte i els dubtes de mesurament abans de definir la fusteria."], ["Configuració i sistemes", "T’ajudem a valorar obertures, perfils i prestacions segons l’obra i el pressupost."], ["Assistència tècnica", "Estudiem les solucions constructives i acordem l’assistència que necessita cada projecte."]],
      steps: [["Identifiquem el dubte", "Comparteix plànols, fotografies, mides i la decisió tècnica que necessites resoldre."], ["Definim la solució", "Revisem els condicionants i concretem la configuració de les fusteries."], ["Acompanyem el projecte", "Coordinem subministrament i suport tècnic amb l’abast acordat per a l’obra."]],
      faq: [["El meu equip continua instal·lant?", "Sí. El teu equip fa la instal·lació amb el nostre suport tècnic acordat."], ["Podeu assistir directament a l’obra?", "Podem valorar assistència a l’obra segons el projecte. Si el teu equip comença, consulta la primera instal·lació assistida."], ["Quina documentació convé enviar?", "Els plànols disponibles, fotografies dels buits, mides orientatives i les necessitats d’obertura, aïllament o acabat."]],
      cta: "Consultar suport tècnic", alt: "Visualització d’una revisió tècnica de perfils de PVC i alumini",
    },
    instalacion: {
      label: "Subministrament + instal·lació", title: "Instal·lació de finestres per a les teves obres.",
      description: "Mesurament, subministrament i instal·lació de fusteria exterior per a empreses de reforma i construcció a Catalunya.",
      intro: "Delega la partida de fusteria exterior. Ens encarreguem de mesurar, subministrar i instal·lar, coordinant-nos amb la planificació de l’obra.",
      fit: "Per a constructores, empreses de reforma i interioristes que prefereixen un únic responsable de la fusteria exterior.",
      includes: [["Mesurament i definició", "Revisem els buits i les necessitats del projecte abans del subministrament."], ["Subministrament coordinat", "Seleccionem i subministrem les finestres de PVC o alumini segons la solució acordada."], ["Instal·lació i acabats", "Ens encarreguem del muntatge i els acabats de la partida, coordinant-nos amb la resta de l’obra."]],
      steps: [["Coneixem l’obra", "Explica’ns la ubicació, el nombre d’unitats i l’estat del projecte."], ["Acordem l’abast", "Concretem mesuraments, sistema, acabats, condicions i coordinació."], ["Resolem la partida", "Organitzem subministrament i instal·lació i revisem el funcionament de la fusteria."]],
      faq: [["Inclou el mesurament?", "Sí. Aquesta modalitat reuneix mesurament, subministrament i instal·lació de la fusteria acordada."], ["Treballeu amb el meu equip de reforma?", "Sí. Ens coordinem amb els responsables per organitzar la intervenció i les trobades amb altres treballs."], ["Podeu renovar fusteries existents?", "Sí. Estudiem les substitucions segons l’estat dels buits i les necessitats de la reforma. L’abast es concreta a la proposta."]],
      cta: "Consultar instal·lació completa", alt: "Visualització d’una comprovació de nivell en instal·lar una finestra",
    },
    "asesoramiento-tecnico": {
      label: "Assessorament tècnic a l’obra", title: "Assessorament tècnic per instal·lar a la teva obra.",
      description: "Assessorament tècnic i acompanyament en les primeres instal·lacions de finestres de PVC i alumini per a equips professionals a Catalunya.",
      intro: "Si la teva empresa vol incorporar la instal·lació de finestres, acompanyem el teu equip en els primers treballs amb assistència tècnica a l’obra.",
      fit: "Per a empreses que volen desenvolupar la capacitat d’instal·lar fusteria de PVC o alumini amb el seu equip.",
      includes: [["Preparació de la instal·lació", "Revisem el sistema i les qüestions tècniques que cal resoldre abans del muntatge."], ["Acompanyament pràctic", "Us ajudem durant la primera instal·lació, resolent els dubtes del treball real."], ["Autonomia progressiva", "L’objectiu és que l’equip entengui el procés i guanyi autonomia amb suport adaptat a la seva experiència."]],
      steps: [["Explica’ns el punt de partida", "Necessitem conèixer l’experiència de l’equip, el sistema i les característiques de la primera obra."], ["Planifiquem l’assistència", "Acordem abast, desplaçament i acompanyament segons les unitats i necessitats."], ["Resolem els dubtes a l’obra", "Acompanyem el treball i resolem les qüestions tècniques amb el vostre equip."]],
      faq: [["En què consisteix l’assessorament?", "Revisem amb el vostre equip les qüestions tècniques de la instal·lació i acompanyem el treball segons l’abast acordat."], ["Hi ha un preu fix?", "La proposta s’adapta al projecte, desplaçament, unitats i necessitats de l’equip. Consulta’ns per concretar-la."], ["També subministreu les finestres?", "Sí. Podem combinar el subministrament amb l’acompanyament en les primeres instal·lacions."]],
      cta: "Consultar assessorament tècnic", alt: "Visualització d’un tècnic acompanyant un professional en la instal·lació d’una finestra",
      secondaryTitle: "Entendre el sistema també forma part del treball.", secondaryText: "Revisar perfils, juntes i trobades ajuda a plantejar les preguntes adequades abans d’instal·lar. Adaptem el suport als sistemes i a l’experiència del teu equip.",
    },
  },
  en: {
    suministro: {
      label: "Supply only", title: "Window supply for construction professionals.",
      description: "PVC and aluminium windows for renovation and construction companies in Catalonia. Trade terms and delivery to your site.",
      intro: "Your team handles installation. We supply the windows your project needs, configured for the requirements of your site.",
      fit: "For companies with their own installers looking for a partner to handle window supply.",
      includes: [["Made-to-measure windows", "PVC and aluminium windows configured to your dimensions, opening types and finishes."], ["Systems for your project", "We work with REHAU PVC and INDALSU and STRUGAL aluminium systems, selected to suit performance and budget."], ["Site delivery", "We coordinate supply and delivery with you. Lead times are agreed for each proposal."]],
      steps: [["Share your project", "Send dimensions, quantities, location and the requirements you have already defined."], ["Confirm the configuration", "We agree systems, finishes and terms before confirming supply."], ["Coordinate delivery", "We agree delivery so your team can plan installation."]],
      faq: [["Is installation included?", "This option is designed for your team to install. To delegate measuring and installation, see our complete service."], ["Can I add technical support?", "Yes. We can extend our collaboration to include technical review and assistance for your project."], ["How is the price calculated?", "We prepare a trade proposal based on systems, dimensions, quantities and finishes. We need your project details to quote."]],
      cta: "Discuss window supply", alt: "Illustration of aluminium windows in a Mediterranean residential project",
    },
    "apoyo-tecnico": {
      label: "Supply + technical support", title: "Window supply with technical support.",
      description: "Technical support for exterior windows in Catalonia: measurement review, configuration and construction details with PVC and aluminium supply.",
      intro: "Your team stays in charge of installation. We support technical decisions so the windows fit the project.",
      fit: "For professionals with their own installers who need help with measurements, junction details or configuration.",
      includes: [["Measurement review", "We review project information and measurement questions before specifying the windows."], ["Configuration and systems", "We help you assess opening types, profiles and performance for the project and budget."], ["Technical assistance", "We discuss construction details and agree the support each project needs."]],
      steps: [["Identify the question", "Share drawings, photos, dimensions and the technical decision you need to resolve."], ["Define the solution", "We review the constraints together and agree the window configuration."], ["Support your project", "We coordinate supply and technical support within the agreed scope."]],
      faq: [["Does my team still install?", "Yes. Your team carries out installation with our agreed technical support."], ["Can you help on site?", "We can assess on-site assistance for your project. If your team is starting out, explore assisted first installation."], ["What information should I send?", "Available drawings, photos of the openings, approximate measurements and opening, insulation or finish requirements."]],
      cta: "Discuss technical support", alt: "Illustration of a technical review of PVC and aluminium profiles",
    },
    instalacion: {
      label: "Supply + installation", title: "Window installation for your building projects.",
      description: "Measurement, supply and installation of exterior windows for renovation and construction companies across Catalonia.",
      intro: "Delegate the window package. We handle measurement, supply and installation in coordination with your site schedule.",
      fit: "For builders, renovation companies and interior designers who want one responsible partner for exterior windows.",
      includes: [["Measurement and specification", "We review openings and project requirements before supply."], ["Coordinated supply", "We select and supply PVC or aluminium windows to the agreed specification."], ["Installation and finishing", "We handle fitting and finishing within the window package, coordinating with other site work."]],
      steps: [["Tell us about the site", "Share the location, number of units and current project stage."], ["Agree the scope", "We confirm measurements, system, finishes, terms and installation coordination."], ["Complete the window package", "We organise supply and installation and check window operation."]],
      faq: [["Is measurement included?", "Yes. This option combines measurement, supply and installation of the agreed windows."], ["Do you work alongside my renovation team?", "Yes. We coordinate with the site team to plan our work and its junctions with other trades."], ["Can you replace existing windows?", "Yes. We assess replacement based on the condition of the openings and renovation requirements. Scope is agreed in the proposal."]],
      cta: "Discuss full installation", alt: "Illustration of a window installation being checked with a spirit level",
    },
    "asesoramiento-tecnico": {
      label: "On-site technical advice", title: "Technical advice for installations on your site.",
      description: "Technical advice and support for first PVC and aluminium window installations for professional construction teams in Catalonia.",
      intro: "If your company wants to start installing windows, we support your team through its first projects with technical assistance on site.",
      fit: "For companies developing the ability to install PVC or aluminium windows with their own team.",
      includes: [["Installation preparation", "We review the system and the technical questions to resolve before fitting."], ["Practical guidance", "We help during the first installation, answering questions as the work progresses."], ["Growing independence", "The aim is for your team to understand the process and gain independence with support matched to its experience."]],
      steps: [["Tell us your starting point", "We need to know your team’s experience, the system and the first project’s requirements."], ["Plan the assistance", "We agree scope, travel and support based on unit numbers and project needs."], ["Resolve questions on site", "We support the work and resolve technical questions alongside your team."]],
      faq: [["What does technical advice involve?", "We review installation questions with your team and support the work on site within the agreed scope."], ["Is there a fixed price?", "The proposal depends on the project, travel, unit numbers and team needs. Contact us to discuss the details."], ["Do you also supply the windows?", "Yes. We can combine window supply with support during your first installations."]],
      cta: "Discuss technical advice", alt: "Illustration of an experienced technician guiding another professional during window installation",
      secondaryTitle: "Understanding the system is part of the job.", secondaryText: "Reviewing profiles, gaskets and junctions helps you ask the right questions before installation. We tailor support to the systems and your team’s experience.",
    },
  },
};
export const professionalLabels = {
  es: { home:"Inicio",overview:"Profesionales",includes:"Qué incluye",fit:"Cuándo elegir esta opción",process:"Cómo trabajamos",questions:"Antes de empezar",related:"Otras formas de colaborar",contact:"Hablemos de tu proyecto",contactText:"Cuéntanos qué necesitas y concretamos contigo el alcance de la colaboración.",back:"Ver todas las opciones",imageNote:"Imagen ilustrativa generada con IA.",secondaryAlt:"Visualización de una explicación práctica con muestras de perfiles de ventanas",location:"Barcelona · Toda Cataluña" },
  ca: { home:"Inici",overview:"Professionals",includes:"Què inclou",fit:"Quan triar aquesta opció",process:"Com treballem",questions:"Abans de començar",related:"Altres formes de col·laborar",contact:"Parlem del teu projecte",contactText:"Explica’ns què necessites i concretem l’abast de la col·laboració.",back:"Veure totes les opcions",imageNote:"Imatge il·lustrativa generada amb IA.",secondaryAlt:"Visualització d’una explicació pràctica amb mostres de perfils de finestres",location:"Barcelona · Tot Catalunya" },
  en: { home:"Home",overview:"Professionals",includes:"What’s included",fit:"When to choose this option",process:"How we work",questions:"Before you start",related:"Other ways to work together",contact:"Let’s discuss your project",contactText:"Tell us what you need and we’ll agree the scope of our collaboration.",back:"Explore all options",imageNote:"Illustrative image generated with AI.",secondaryAlt:"Illustration of a practical explanation using window profile samples",location:"Barcelona · Across Catalonia" },
};
