import React, {createContext, useContext, useEffect, useState} from "react";

const copy={
es:{services:"Servicios",about:"Sobre nosotros",contact:"Contacto",quote:"Solicitar presupuesto",location:"Barcelona · Toda Cataluña",heroTitle:"Espacios que",heroAccent:"respiran.",heroText:"Cerramientos, ventanas y protección solar a medida para conectar tu hogar con la luz y el paisaje.",talk:"Hablemos de tu proyecto",solutions:"Ver soluciones",serviceKick:"Nuestras soluciones",serviceTitle:"Diseño que mejora cómo vives.",serviceLead:"De la primera medición al último ajuste. Una mirada integral para crear cerramientos eficientes, precisos y naturalmente bellos.",catalog:"Soluciones Finestra",catalogTitle:"Un universo de posibilidades para tu espacio.",catalogLead:"Cada proyecto empieza escuchando. Diseñamos, fabricamos e instalamos soluciones precisas para mejorar la luz, el confort y la forma de habitar.",companyKick:"Nuestra forma de hacer",companyTitle:"La precisión también puede sentirse.",companyHead:"Más que instalar. Transformamos espacios.",companyP1:"En Finestra Serveis combinamos oficio, tecnología y sensibilidad arquitectónica para resolver cada proyecto con precisión.",companyP2:"Escuchamos cómo vives, estudiamos la luz y elegimos el sistema adecuado. El resultado son espacios más confortables, eficientes y conectados con su entorno.",contactTitle:"Solicita tu presupuesto",contactText:"Cuéntanos qué necesitas y nuestro equipo te responderá con una solución personalizada.",send:"Enviar solicitud",name:"Nombre",email:"Email",phone:"Teléfono",message:"Mensaje (mínimo 10 palabras)"},
ca:{services:"Serveis",about:"Sobre nosaltres",contact:"Contacte",quote:"Demanar pressupost",location:"Barcelona · Tot Catalunya",heroTitle:"Espais que",heroAccent:"respiren.",heroText:"Tancaments, finestres i protecció solar a mida per connectar la teva llar amb la llum i el paisatge.",talk:"Parlem del teu projecte",solutions:"Veure solucions",serviceKick:"Les nostres solucions",serviceTitle:"Disseny que millora com vius.",serviceLead:"Des del primer mesurament fins a l'últim ajust. Una mirada integral per crear tancaments eficients, precisos i naturalment bells.",catalog:"Solucions Finestra",catalogTitle:"Un univers de possibilitats per al teu espai.",catalogLead:"Cada projecte comença escoltant. Dissenyem, fabriquem i instal·lem solucions precises per millorar la llum, el confort i la manera d'habitar.",companyKick:"La nostra manera de fer",companyTitle:"La precisió també es pot sentir.",companyHead:"Més que instal·lar. Transformem espais.",companyP1:"A Finestra Serveis combinem ofici, tecnologia i sensibilitat arquitectònica per resoldre cada projecte amb precisió.",companyP2:"Escoltem com vius, estudiem la llum i triem el sistema adequat. El resultat són espais més confortables, eficients i connectats amb l'entorn.",contactTitle:"Demana el teu pressupost",contactText:"Explica'ns què necessites i el nostre equip et respondrà amb una solució personalitzada.",send:"Enviar sol·licitud",name:"Nom",email:"Correu electrònic",phone:"Telèfon",message:"Missatge (mínim 10 paraules)"},
en:{services:"Solutions",about:"About us",contact:"Contact",quote:"Request a quote",location:"Barcelona · Across Catalonia",heroTitle:"Spaces that",heroAccent:"breathe.",heroText:"Bespoke windows, enclosures and solar protection that connect your home with light and landscape.",talk:"Let's discuss your project",solutions:"Explore solutions",serviceKick:"Our solutions",serviceTitle:"Design that improves how you live.",serviceLead:"From the first measurement to the final adjustment. A complete approach to efficient, precise and naturally beautiful enclosures.",catalog:"Finestra solutions",catalogTitle:"A world of possibilities for your space.",catalogLead:"Every project begins by listening. We design, manufacture and install precise solutions that improve light, comfort and the way you live.",companyKick:"The way we work",companyTitle:"Precision you can feel.",companyHead:"More than installation. We transform spaces.",companyP1:"At Finestra Serveis we combine craftsmanship, technology and architectural sensitivity to deliver every project with precision.",companyP2:"We listen to how you live, study the light and select the right system. The result is a more comfortable, efficient space connected to its surroundings.",contactTitle:"Request your quote",contactText:"Tell us what you need and our team will reply with a tailored solution.",send:"Send request",name:"Name",email:"Email",phone:"Phone",message:"Message (minimum 10 words)"}
};
const Ctx=createContext();
export function LanguageProvider({children}){const [lang,setLang]=useState(()=>localStorage.getItem("finestra-lang")||"es");useEffect(()=>{localStorage.setItem("finestra-lang",lang);document.documentElement.lang=lang},[lang]);return <Ctx.Provider value={{lang,setLang,t:(key)=>copy[lang][key]||copy.es[key]||key}}>{children}</Ctx.Provider>}
export const useLanguage=()=>useContext(Ctx);
